version: "3"

services:
  green-bm:
    image: node:19.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node
    working_dir: /home/node

  pocket-base:
    image: augustodelg/pocketbase:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - pocket-base-data:/pb_data

volumes:
  pocket-base-data: